replicaCount: 2

image:
  repository: chandu554/attendance-service-lb
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3004

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
